### ISSUE TITLE
Проблема с ALT

### ISSUE THREAD

**Issue by webdesus** [reconquest/rex#2]
Ни кто не сталкивался с проблемой альта в GTK программах. Я пытаюсь сделать перемещение курсора по hjkl с нажатым альтом. Но приходит постоянно alt+Стрелка. ClearMods не работает. С другими кнопками получается настроить данное поведение а вот с альтом и win кнопками нет. Мой [конф](https://github.com/webdesus/dotfiles/tree/master/xkb). Случаем не знаете в чем может быть проблема? А то уже несколько дней ищу способ решения. Уже много чего из инета перепробовал но не нашел рабочего примера.

**Comment by seletskiy** [comment]
@webdesus: а в чём не работает, например?

**Comment by seletskiy** [comment]
@webdesus: проверил в geany, работает.

**Comment by webdesus** [comment]
double commander

**Comment by webdesus** [comment]
terminal

**Comment by seletskiy** [comment]
@webdesus: проверил, работает. Попробуй скопировать xkb-конфиги полностью и использовать файл с конфигурацией, например — https://github.com/kovetskiy/dotfiles/blob/master/.xkbrc

Когда запускаешь xkbcomp, посмотри вывод, там могут быть ошибки.

**Comment by webdesus** [comment]
Я выполняю следующую команду
xkbcomp -w 0 -I$HOME/dotfiles/rex-master -R$HOME/dotfiles/rex-master $HOME/dotfiles/rex-master/xkb $DISPLAYD

Выскакивают ошибки. у меня с LVL3 тоже в моем конфиге происходит конфликт, но я всегда думал что это информационное сообщение. ведь он пишет что используйте Mod4 который мы и задаем в конфиге а Mod5 который был до нас игнорируем


Error:            Key <LVL3> added to map for multiple modifiers
                  Using Mod4, ignoring Mod5.
Error:            Key <MDSW> added to map for multiple modifiers
                  Using Mod3, ignoring Mod5.

**Comment by webdesus** [comment]
А какой дистрибутив Вы используете? У меня последний минт.

**Comment by seletskiy** [comment]
@webdesus: archlinux. Хочу заметить, что в приложеной конфигурации Alt+hjkl хоть и работает как стрелки, но на самом деле Alt перемаплен на Win, т.е. по факту обрабатывается нажатие Win+hjkl.

**Comment by kovetskiy** [comment]
@webdesus проверил на конфиге https://github.com/kovetskiy/dotfiles/blob/master/.xkbrc double commander gtk2 — работает.

**Comment by webdesus** [comment]
Я так и думал что полноценно работает только в archlinux. Я находил кучу мест что это баг убунты. Но все рецепты приводимые не работают. По ходу проблема до сих пор в дебиане жива. Все очень странно. Буду тогда искать способы иначе бороться со своим горем)))

**Comment by kovetskiy** [comment]
@webdesus https://wiki.archlinux.org/index.php/Install_from_existing_Linux + https://wiki.archlinux.org/index.php/Installation_guide

У всех страданий есть причины, существует путь избавления от страданий, для начала — Arch Linux.

Будут вопросы — пиши, поможем!

**Comment by webdesus** [comment]
😂 я на самом деле весь вечер уже думаю об этом))) либо на arch перейти либо переучить себя пользоваться альтом как капсом. Нажал работают  стрелки, еще раз нажал снова буквы, так я научился работать. Просто с дебайном лет 10 уже и решил и на работе на него перейти. А где то лет 5 как я на винде пользуюсь AutoHotkey с кучей настроек. Которые как оказывается не так легко перенести... 

В любом случае спасибо за отклик. Благодаря ему я хоть понял где искать причину)))

**Comment by webdesus** [comment]
Последний вопрос))) А вы не пользуетесь virtualbox или rdp? в данные программы нормально передаются хоткеи?

**Comment by seletskiy** [comment]
@webdesus: так себе работают, передаются правильно, но если альт перемаплен на win, то окно будет получать дополнительно win.

**Comment by webdesus** [comment]
А значит проблема все таки есть. Я настраиваю на альт и получаю доп альт. Видимо у вас дабл командер кьютешный. Там все работает правильно. Все-таки баг затрагивает и ваш дистр)))

**Comment by seletskiy** [comment]
@webdesus: нет, я специально ставил gtk-шный:

```
14:53 : pps double commander
community/doublecmd-gtk2 0.7.8-1
    twin-panel (commander-style) file manager (GTK)
community/doublecmd-qt 0.7.8-1
    twin-panel (commander-style) file manager (QT)
```

**Comment by webdesus** [comment]
Я в итоге смог это дело победить))) Поиски в интере оказались безрезультатными. Пришлось изучать дефолтные настройки. 
Добавил в xkb_keycodes следующий код:
`<FK13> = 64;`
После чего переопределил xkb_symbols
`modifier_map Mod3 { <FK13> };    
modifier_map Mod3 { <LVL3> };
`
Помню как то давно наверное в AutoHotKey прибегал к такому подходу биндить какие либо действия на не существующую кнопку F13))) Так у меня и в rdp и в virtualbox все работает:relaxed:

**Comment by webdesus** [comment]
И да еще раз спасибо что были со мной все это время)))

**Comment by kovetskiy** [comment]
@webdesus пожалуйста, заходи ещё, всегда рады адептам.
